// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Editor Wails服务结构体
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * BatchEdit 批量编辑图片
 * 前端调用格式：await editor.BatchEdit(imageDataList, options)
 * @param {string[]} imageDataList
 * @param {string} options
 * @returns {$CancellablePromise<string>}
 */
export function BatchEdit(imageDataList, options) {
    return $Call.ByID(2137529314, imageDataList, options);
}

/**
 * BatchSaveToZip 批量保存图片到ZIP文件
 * 前端调用格式：await editor.BatchSaveToZip(imageDataList, zipPath, zipFilename, filenames)
 * @param {string[]} imageDataList
 * @param {string} zipPath
 * @param {string} zipFilename
 * @param {string} filenames
 * @returns {$CancellablePromise<string>}
 */
export function BatchSaveToZip(imageDataList, zipPath, zipFilename, filenames) {
    return $Call.ByID(1287564965, imageDataList, zipPath, zipFilename, filenames);
}

/**
 * EditImage 编辑单张图片
 * 前端调用格式：await editor.EditImage(imageData, options)
 * 返回base64编码的编辑结果和统计信息
 * @param {string} imageData
 * @param {string} options
 * @returns {$CancellablePromise<string>}
 */
export function EditImage(imageData, options) {
    return $Call.ByID(332266035, imageData, options);
}

/**
 * OpenFileDialog 打开文件选择对话框（支持多选）
 * 前端调用格式：await editor.OpenFileDialog()
 * 返回文件路径数组，前端需要调用 ReadImageFile 读取内容
 * @returns {$CancellablePromise<string[]>}
 */
export function OpenFileDialog() {
    return $Call.ByID(3117314364).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ReadImageFile 读取图片文件并返回base64编码
 * 前端调用格式：await editor.ReadImageFile(filePath)
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadImageFile(filePath) {
    return $Call.ByID(4147927297, filePath);
}

/**
 * SaveFileDialog 打开文件保存对话框
 * 前端调用格式：await editor.SaveFileDialog(defaultName, content, mimeType)
 * 返回保存的文件路径
 * @param {string} defaultName
 * @param {string} content
 * @param {string} mimeType
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileDialog(defaultName, content, mimeType) {
    return $Call.ByID(3769667669, defaultName, content, mimeType);
}

/**
 * SaveImage 保存图片到本地
 * 前端调用格式：await editor.SaveImage(imageData, path, filename, overwrite)
 * @param {string} imageData
 * @param {string} path
 * @param {string} filename
 * @param {boolean} overwrite
 * @returns {$CancellablePromise<string>}
 */
export function SaveImage(imageData, path, filename, overwrite) {
    return $Call.ByID(541921092, imageData, path, filename, overwrite);
}

/**
 * SelectDirectoryDialog 打开目录选择对话框
 * 前端调用格式：await editor.SelectDirectoryDialog(defaultPath)
 * 返回选择的目录路径
 * @param {string} defaultPath
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectoryDialog(defaultPath) {
    return $Call.ByID(4118074557, defaultPath);
}

/**
 * Shutdown Wails应用关闭时调用
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2230120004);
}

/**
 * Startup Wails应用启动时调用
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(113059079);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
