// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Compressor Wails服务结构体
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * BatchCompress 批量压缩图片
 * 前端调用格式：await compressor.BatchCompress(imageDataList, options)
 * @param {string[]} imageDataList
 * @param {string} options
 * @returns {$CancellablePromise<string>}
 */
export function BatchCompress(imageDataList, options) {
    return $Call.ByID(2330914346, imageDataList, options);
}

/**
 * BatchSaveToZip 批量保存图片到ZIP文件
 * 前端调用格式：await compressor.BatchSaveToZip(imageDataList, zipPath, zipFilename, filenames)
 * @param {string[]} imageDataList
 * @param {string} zipPath
 * @param {string} zipFilename
 * @param {string} filenames
 * @returns {$CancellablePromise<string>}
 */
export function BatchSaveToZip(imageDataList, zipPath, zipFilename, filenames) {
    return $Call.ByID(4201662489, imageDataList, zipPath, zipFilename, filenames);
}

/**
 * CompressImage 压缩单张图片
 * 前端调用格式：await compressor.CompressImage(imageData, options)
 * 返回base64编码的压缩结果和统计信息
 * @param {string} imageData
 * @param {string} options
 * @returns {$CancellablePromise<string>}
 */
export function CompressImage(imageData, options) {
    return $Call.ByID(800240811, imageData, options);
}

/**
 * GetImageInfo 获取图片信息
 * 前端调用格式：await compressor.GetImageInfo(imageData)
 * 返回base64编码的图片信息和文件大小
 * @param {string} imageData
 * @returns {$CancellablePromise<string>}
 */
export function GetImageInfo(imageData) {
    return $Call.ByID(1708414443, imageData);
}

/**
 * OpenFileDialog 打开文件选择对话框（支持多选）
 * 前端调用格式：await compressor.OpenFileDialog()
 * 返回文件路径数组，前端需要调用 ReadImageFile 读取内容
 * @returns {$CancellablePromise<string[]>}
 */
export function OpenFileDialog() {
    return $Call.ByID(1054749816).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ReadImageFile 读取图片文件并返回base64编码
 * 前端调用格式：await compressor.ReadImageFile(filePath)
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadImageFile(filePath) {
    return $Call.ByID(3314671093, filePath);
}

/**
 * SaveFileDialog 打开文件保存对话框并保存内容
 * 前端调用格式：await compressor.SaveFileDialog(defaultName, content, mimeType)
 * 返回保存的文件路径
 * @param {string} defaultName
 * @param {string} content
 * @param {string} mimeType
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileDialog(defaultName, content, mimeType) {
    return $Call.ByID(3875621801, defaultName, content, mimeType);
}

/**
 * SaveImage 保存图片到本地
 * 前端调用格式：await compressor.SaveImage(imageData, path, filename)
 * @param {string} imageData
 * @param {string} path
 * @param {string} filename
 * @param {boolean} overwrite
 * @returns {$CancellablePromise<string>}
 */
export function SaveImage(imageData, path, filename, overwrite) {
    return $Call.ByID(912217856, imageData, path, filename, overwrite);
}

/**
 * SelectDirectoryDialog 打开目录选择对话框
 * 前端调用格式：await compressor.SelectDirectoryDialog(defaultPath)
 * 返回选择的目录路径
 * @param {string} defaultPath
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectoryDialog(defaultPath) {
    return $Call.ByID(31938289, defaultPath);
}

/**
 * Shutdown Wails应用关闭时调用
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(707996672);
}

/**
 * Startup Wails应用启动时调用
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(3099005571);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
